# Copyright skoved
# SPDX-License-Identifier: MIT
---
header:
  license:
    spdx-id: MIT
    copyright-owner: skoved
    pattern: |
      Copyright skoved
      SPDX-License-Identifier: MIT

  paths-ignore:
    - 'dist'
    - 'licenses'
    - 'LICENSE'
    - 'NOTICE'
    - 'go.mod'
    - 'go.sum'
    - '*.md'

  comment: on-failure
