# Copyright skoved
# SPDX-License-Identifier: MIT
---
name: Linting
run-name: Linting
on:
  pull_request:
    branches:
      - main
permissions:
  contents: read
  pull-requests: write
jobs:
  go-mod-tidy:
    name: Go Mod Tidy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Run go mod tidy
        run: go mod tidy
      - name: Fail if There Are Changes
        run: |
          set -x
          # check if go.sum exists
          if [ -f go.sum ]; then
            git diff --exit-code go.sum
          fi
          git diff --exit-code go.mod
  yamllint:
    name: Yaml Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Run yamllint
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_comment: true
        env: ${{ secrets.GITHUB_TOKEN }}
  golangci-lint:
    name: Golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Display Go Version
        run: go version
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
  check-license-headers:
    name: Check License Headers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Check Licenses
        uses: apache/skywalking-eyes/header@v0.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
