# Copyright skoved
# SPDX-License-Identifier: MIT
---
name: Release
on:
  push:
    tags:
      - "v*"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
permissions:
  contents: write
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Test
        run: |
          set -x
          go build -o roll -v ./...
          go test -v ./...
          rm roll
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: gorleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Go Module
        run: GOPROXY=proxy.go.org go list -m github.com/${GITHUB_REPOSITORY}@${GITHUB_REF_NAME}
